name: CyanShop
version: ${version}
main: cn.cyanbukkit.copy.CyanShop
depend:
  - Citizens
  - Vault
  - PlayerPoints
  - CYANKOTLINLOADER
  - PlaceholderAPI
permissions:
  CyanShop.+:
      description: CyanShop admin permission
      default: op